### ISSUE TITLE
How to handle with the keyboard?

### ISSUE THREAD

**Issue by 3runoDesign** [joomcode/BottomSheet#16]
Hi, how can we handle the keyboard?

**Comment by mikhailmaslo** [comment]
Hi! Thank you for your question, it may seem not trivial but indeed it shouldn't be hard

I've created an example in a [separate branch](https://github.com/joomcode/BottomSheet/tree/feature/scrollview-with-keyboard-example), here is the only [change](https://github.com/joomcode/BottomSheet/compare/main...feature/scrollview-with-keyboard-example) in the branch. When we calculate `preferredContentSize` we should consider keyboard hight along with `scrollView.contentSize`.

If everything is done right, you should get smooth animation on keyboard (dis)appearance, like in this demo

https://github.com/joomcode/BottomSheet/assets/52037202/385d3c76-7d64-4f39-b8b8-e137d4c4bf2a

**Comment by mikhailmaslo** [comment]
I will close it for now, but feel free if you provided example above doesn't work for you
