### ISSUE TITLE
More customisation options

### ISSUE THREAD

**Issue by BhavinBhadani** [joomcode/BottomSheet#17]
I want to know if we do have a more configuration options like blur intensity, dismiss pan and tap gesture? Currently I think pan gesture needs to work with few methods but I think we can do it by single boolean value.

**Comment by mikhailmaslo** [comment]
My apologies for late response

> I want to know if we do have a more configuration options like blur intensity, dismiss pan and tap gesture

1. blur intensity - partly the work was done here and my comment about it is here https://github.com/joomcode/BottomSheet/pull/15#pullrequestreview-1333060793
2. dismiss pan and tap gesture - those are partly customizable by `canBeDismissed: Bool` property in [BottomSheetModalDismissalHandler.swift](https://github.com/joomcode/BottomSheet/blob/b847e09e40a833593b29475f2f1c94e8260befe2/Sources/BottomSheet/Core/Presentation/BottomSheetModalDismissalHandler.swift#L10). With [default implementation](https://github.com/joomcode/BottomSheet/blob/b847e09e40a833593b29475f2f1c94e8260befe2/Sources/BottomSheet/Core/Extensions/UIViewController%2BConvenience.swift#L64) to always allow dismissing. If you'd like to have more customization over those gestures - let me know which exactly customization you expect

> Currently I think pan gesture needs to work with few methods but I think we can do it by single boolean value.

Can you elaborate what which method and what's implementation?

**Comment by BhavinBhadani** [comment]
Thanks @mikhailmaslo Let me go through the same and will let you know
