### ISSUE TITLE
navigationcontroller init problem in iOS 12

### ISSUE THREAD

**Issue by mohabbasi1213** [joomcode/BottomSheet#18]
Fatal error: Use of unimplemented initializer 'init(nibName:bundle:)' for class 'BottomSheet.BottomSheetNavigationController'

**Comment by mikhailmaslo** [comment]
Hi, it's not intended for storyboard usage

**Comment by mohabbasi1213** [comment]
this is happening for me on iOS 12 for BottomSheetDemo on the project.
but it is working properly on iOS 16.

**Comment by mikhailmaslo** [comment]
Do you use it inside a Storyboard?

**Comment by mohabbasi1213** [comment]
No, I run your demo without any storyboard file inside the project.

**Comment by mikhailmaslo** [comment]
Can you tell me your Xcode version?

**Comment by mohabbasi1213** [comment]
Version 14.2 (14C18)
test device: iPhone 6 - iOS 12.4.9

**Comment by luka-w** [comment]
Same problem, xCode 14.3, device: iPhone 5S, iOS 12.5.7

**Comment by mikhailmaslo** [comment]
It should be fixed as soon as we merge https://github.com/joomcode/BottomSheet/pull/21

**Comment by mikhailmaslo** [comment]
Should be fixed in `main` and release `2.0.3`

Feel free to reopen, if it's the case
