### ISSUE TITLE
didSelectRowAt indexPath: IndexPath

### ISSUE THREAD

**Issue by snazarovone** [joomcode/BottomSheet#2]
Столкнулся с проблемой вызова метода didSelectRowAt табличного представления, ячейка подсвечивается цветом, но события не приходит в метод didSelectRowAt 

возможно где то не выставлено свойство жеста cancelsTouchesInView = false

**Comment by mikhailmaslo** [comment]
Привет! Можешь подсказать, сохраняется ли проблема, если показывать `UITableView` без использования `BottomSheetTransitioningDelegate` (то есть показать экран без BottomSheet)?

Если да, то хорошо бы дать доступ к тестовому проекту, в котором будет понятно, как используется `BottomSheet` и `UITableView`

**Comment by snazarovone** [comment]
Проблема сохраняется если viewController подписан под протокол ScrollableBottomSheetPresentedController

Возможно я не правильно использовал, Ваш, код для того чтобы применить его в связке с tableView, не могли бы, Вы в таком случае дать такой пример?

Вот тестовый проект: https://github.com/snazarovone/BottomSheet

**Comment by mikhailmaslo** [comment]
@snazarovone Спасибо за пример и репорт бага

Попробуй на актуальном `main`, должно было пофикситься

**Comment by mikhailmaslo** [comment]
Закрываю issue, раз дополнений нет
