### ISSUE TITLE
BottomSheet is presented over TabBar

### ISSUE THREAD

**Issue by ewan34500** [joomcode/BottomSheet#25]
Hello,

I am currently using your library for a project and I'm encountering an issue where the BottomSheet is presented over the TabBar. I would like the TabBar to remain visible when the BottomSheet is presented.

Here is the code I'm using to present the BottomSheet:

```self.presentBottomSheet(
    viewController: ModalviewController,
    configuration: BottomSheetConfiguration(
        cornerRadius: 10,
        pullBarConfiguration: .visible(.init(height: 20)),
        shadowConfiguration: .init(backgroundColor: UIColor.black.withAlphaComponent(0.6))
    ),
    canBeDismissed: {
        true
    },
    dismissCompletion: {
    }
)
```

I've tried presenting the BottomSheet from the TabBarController itself, but this did not solve the issue. Here's the code for that attempt:

```self.tabBarController?.presentBottomSheet(
    viewController: ModalviewController,
    configuration: BottomSheetConfiguration(
        cornerRadius: 10,
        pullBarConfiguration: .visible(.init(height: 20)),
        shadowConfiguration: .init(backgroundColor: UIColor.black.withAlphaComponent(0.6))
    ),
    canBeDismissed: {
        true
    },
    dismissCompletion: {
    }
)
```

Is there a solution or workaround for this problem? Any guidance would be much appreciated.

**Comment by mikhailmaslo** [comment]
Hi!

I suppose it should be somehow considered inside bottom sheet transition, thus won't work out of the box

**Comment by ewan34500** [comment]
So there is no way to use like I want?

**Comment by mikhailmaslo** [comment]
Yes, there is no way to use it like this. And it needs additional development

**Comment by mikhailmaslo** [comment]
Closing the issue, seems there will be no further progress at this moment
