### ISSUE TITLE
Cannot find option to disable dismiss

### ISSUE THREAD

**Issue by sthahemant1st** [joomcode/BottomSheet#26]
presentBottomSheet(
    viewController: viewControllerToPresent,
    configuration: BottomSheetConfiguration(
        cornerRadius: 10,
        pullBarConfiguration: .visible(.init(height: 20)),
        shadowConfiguration: .init(backgroundColor: UIColor.black.withAlphaComponent(0.6))
    ),
    canBeDismissed: {
        // return `true` or `false` based on your business logic
        true
    },
    dismissCompletion: {
        // handle dismiss completion if user closed bottom sheet by a gesture
    }
)
I can't find above function which allows me to pass canBeDismissed. Can anyone help me

**Comment by mikhailmaslo** [comment]
Hi, do you use latest [2.0.3](https://github.com/joomcode/BottomSheet/releases/tag/2.0.3)? It was added only in 2.0.3 few weeks ago

**Comment by sthahemant1st** [comment]
presentBottomSheet(
    viewController: viewControllerToPresent,
    configuration: BottomSheetConfiguration(
        cornerRadius: 10,
        pullBarConfiguration: .visible(.init(height: 20)),
        shadowConfiguration: .init(backgroundColor: UIColor.black.withAlphaComponent(0.6))
    ),
    canBeDismissed: {
        // return `true` or `false` based on your business logic
        true
    },
    dismissCompletion: {
        // handle dismiss completion if user closed bottom sheet by a gesture
    }
)
Sorry, didn't see above code before "canBeDismissed"
