### ISSUE TITLE
Swipe the botomsheet presented on botomsheet

### ISSUE THREAD

**Issue by VGrokhotov** [joomcode/BottomSheet#27]
I found a strange behaviour, that if botomsheet is presented on botomsheet and we swipe the top one down, both will be dismissed. But if we tap on shadow or call `dismiss` of top one by ourselves, everything will be alright. 

I guess the reason is this method of `BottomSheetPresentationController`:
<img width="874" alt="image" src="https://github.com/joomcode/BottomSheet/assets/50099240/d6f34b1f-e0f0-42c6-8a0d-a8819a1f775f">

The tap works with such a way:
<img width="714" alt="image" src="https://github.com/joomcode/BottomSheet/assets/50099240/fc110e43-6c1a-4ac4-8b94-5675d83fc11f">

Looks like in `startInteractiveTransition` the presenting controller dismisses, so the both bottomsheets dismisses. Can you please change the behavier to dismiss only **presented** bottomshet? All my tries failed 😞

**Comment by VGrokhotov** [comment]
I dismiss with swipe only second bottomsheet, both of bottomsheets dismiss
https://github.com/joomcode/BottomSheet/assets/50099240/4294b6a0-e404-4bcc-a682-6d90cce7594f

The way I show them:
```swift
    func presentAsBottomSheet(_ controller: UIViewController) {
        setPreferredContentSize(controller)
        
        presentBottomSheet(
            viewController: controller,
            configuration: .init(
                cornerRadius: 24,
                pullBarConfiguration: .hidden,
                shadowConfiguration: .init(backgroundColor: .black.withAlphaComponent(0.3), blur: .regular)
            ),
            canBeDismissed: { true },
            dismissCompletion: nil
        )
    }
    
    private func setPreferredContentSize(_ controller: UIViewController) {
        controller.view.layoutIfNeeded()

        let targetSize = CGSize(width: UIScreen.main.bounds.width, height: UIView.layoutFittingExpandedSize.height)
        controller.preferredContentSize = controller.view.systemLayoutSizeFitting(targetSize)
    }
```

**Comment by mikhailmaslo** [comment]
Thank you for the report! I think I found the problem https://github.com/joomcode/BottomSheet/pull/28

If it looks good to you, I will merge it and release a new version

**Comment by VGrokhotov** [comment]
LGTM! Works as expected! Thank you for such a fast fix! @mikhailmaslo

**Comment by mikhailmaslo** [comment]
Great! Then, closing the issue, [version 2.0.4](https://github.com/joomcode/BottomSheet/releases/tag/2.0.4) with the fix was published 🚀 

Thank you again for your contribution!
