### ISSUE TITLE
iOS 17 display bottom sheet below tab bar

### ISSUE THREAD

**Issue by BhavinBhadani** [joomcode/BottomSheet#31]
With iOS 17, the bottom sheet presented under tab bar and not like above tab bar.
![Screenshot 2023-09-28 at 4 47 55 PM](https://github.com/joomcode/BottomSheet/assets/11731407/4abf9acc-b5fc-40a2-93d1-da29d89f6aef)

**Comment by Madara2hor** [comment]
Hi! Did you find solution? I have the same issue

**Comment by BhavinBhadani** [comment]
@Madara2hor  Yeah just presented with tab bar controller

**Comment by Madara2hor** [comment]
> @Madara2hor  Yeah just presented with tab bar controller

So u just hide tab bar or what? In my case I can't just hide it

**Comment by aquila1213** [comment]
would you please consider updating the version, so we can use this? :)
