### ISSUE TITLE
Can we have the property shouldPresentInFullscreen as a config property?

### ISSUE THREAD

**Issue by lcanalimp** [joomcode/BottomSheet#32]
With iOS 17 there is a known issue with BottomSheetPresentationController which can be resolved by setting shouldPresentInFullscreen to true.
It would be necessary to have the possibility to set this value via config in order to solve this problem with iOS 17

**Comment by mikhailmaslo** [comment]
Should be addressed here https://github.com/joomcode/BottomSheet/pull/38
