### ISSUE TITLE
Cannot receive the dismissCompletion event

### ISSUE THREAD

**Issue by LiDevil** [joomcode/BottomSheet#36]
hello ,i am facing a issues that if i using dismiss(animated: true) instead of swipe-down or just tapping on an empty space, the dismissCompletion cannot be received ,how to solve it , thanks you

**Comment by mikhailmaslo** [comment]
Hello @LiDevil!

Thank you for letting me know about this inconsistency. Fixed it here https://github.com/joomcode/BottomSheet/pull/37

May I ask you to take a look at this PR to make sure it addresses your issue? As soon as I'll get your approve, I can merge to the main branch

**Comment by LiDevil** [comment]
> Hello @LiDevil!
> 
> Thank you for letting me know about this inconsistency. Fixed it here #37
> 
> May I ask you to take a look at this PR to make sure it addresses your issue? As soon as I'll get your approve, I can merge to the main branch

Yes, i follow the code change, it fix my pr ,thank you, expecting your update

**Comment by mikhailmaslo** [comment]
Released in [2.0.5](https://github.com/joomcode/BottomSheet/releases/tag/2.0.5)
