### ISSUE TITLE
Is it possible to close BottomSheet by scrolling it down when UITableView is inside?

### ISSUE THREAD

**Issue by vikkiorrikki** [joomcode/BottomSheet#39]
Hello!

Is it possible to close a BottomSheet by scrolling it down when UITableView is inside? (except using `func scrollViewDidScroll(_ scrollView: UIScrollView)`)

For me now it works like this, I scroll down a BottomSheet when UITableView is inside and only UITableView scrolls, but I can not close BottomSheet by doing this.

**Comment by mikhailmaslo** [comment]
Hi! Did you implement https://github.com/joomcode/BottomSheet/blob/15ab2cf96b757b72b09a6515f667685ff55924e1/Sources/BottomSheet/Core/Presentation/BottomSheetPresentationController.swift#L12 in your view controller?

**Comment by vikkiorrikki** [comment]
It helped! Thanks!
