### ISSUE TITLE
BottomSheet does not contain bitcode

### ISSUE THREAD

**Issue by blackorangefox** [joomcode/BottomSheet#9]
Hello,

I have a problem when try create archive in Xcode 14, 
Showing Recent Issues ***/BottomSheet.o' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file ***/BottomSheet.o' for architecture arm64

**Comment by mikhailmaslo** [comment]
Hi @blackorangefox,

Based on [Xcode 14 Release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) bitcode was deprecated 
Here is [quite detailed explanation](https://stackoverflow.com/a/73219854) behind the possible reasons of this deprecation

So, at the end of the day, you probably need to disable bitcode for your project
